export enum GitcoinPassport {
  beginnerCommunityStaker = "BeginnerCommunityStaker",
  brightId = "Brightid",
  civicCaptcha = "CivicCaptchaPass",
  civicLiveness = "CivicLivenessPass",
  civicUniqueness = "CivicUniquenessPass",
  coinbaseDual = "CoinbaseDualVerification",
  discord = "Discord",
  ens = "Ens",
  ethActive50Days = "ETHDaysActive#50",
  ethGasMoreThan025 = "ETHGasSpent#0.25",
  ethTransactionsOver100 = "ETHnumTransactions#100",
  ethEnthusiast = "ETHScore#50",
  ethAdvocate = "ETHScore#75",
  ethMaxi = "ETHScore#90",
  experiencedCommunityStaker = "ExperiencedCommunityStaker",
  gitcoinGrants10 = "GitcoinContributorStatistics#totalContributionAmountGte#10",
  gitcoinGrants100 = "GitcoinContributorStatistics#totalContributionAmountGte#100",
  gitcoinGrants1000 = "GitcoinContributorStatistics#totalContributionAmountGte#1000",
  githubActivity30 = "githubContributionActivityGte#30",
  githubActivity60 = "githubContributionActivityGte#60",
  githubActivity120 = "githubContributionActivityGte#120",
  gnosisSafe = "GnosisSafe",
  google = "Google",
  guildAdmin = "GuildAdmin",
  guildMember = "GuildPassportMember",
  holonymGovIdProvider = "HolonymGovIdProvider",
  idenaStateHuman = "IdenaState#Human",
  idenaStateNewbie = "IdenaState#Newbie",
  idenaStateVerified = "IdenaState#Verified",
  lens = "Lens",
  linkedin = "Linkedin",
  nft = "NFT",
  nftScore50 = "NFTScore#50",
  nftScore75 = "NFTScore#75",
  nftScore90 = "NFTScore#90",
  selfStakingBronze = "SelfStakingBronze",
  selfStakingGold = "SelfStakingGold",
  selfStakingSilver = "SelfStakingSilver",
  snapshotProposalsProvider = "SnapshotProposalsProvider",
  trustaLabs = "TrustaLabs",
  trustedCitizen = "TrustedCitizen",
  zkSyncEra = "ZkSyncEra",
  zkSyncScore20 = "zkSyncScore#20",
  zkSyncScore50 = "zkSyncScore#50",
  zkSyncScore5 = "zkSyncScore#5",
  outdid = "Outdid",
  binanceBABT = "BinanceBABT",
}

const gitcoinPassportData = {
  [GitcoinPassport.beginnerCommunityStaker]: {
    weight: 1.5,
    label: "Beginner Community Staker",
    icon: "gtcStakingLogoIcon.svg",
    category: "GTC Community Staking",
    type: "Blockchain & Crypto Networks",
  },
  [GitcoinPassport.brightId]: {
    weight: 0.8,
    label: "Verified BrightID",
    icon: "brightidStampIcon.svg",
    category: "BrightID",
    type: "Blockchain & Crypto Networks",
  },
  [GitcoinPassport.civicCaptcha]: {
    weight: 1,
    label: "holds a Civic CAPTCHA Pass",
    icon: "civicStampIcon.svg",
    category: "Civic",
    type: "Biometric Verification",
  },
  [GitcoinPassport.civicLiveness]: {
    weight: 3,
    label: "holds a Civic Liveness Pass",
    icon: "civicStampIcon.svg",
    category: "Civic",
    type: "Biometric Verification",
  },
  [GitcoinPassport.civicUniqueness]: {
    weight: 6,
    label: "holds a Civic Uniqueness Pass",
    icon: "civicStampIcon.svg",
    category: "Civic",
    type: "Biometric Verification",
  },
  [GitcoinPassport.coinbaseDual]: {
    weight: 16,
    label: "Coinbase Verified ID",
    icon: "coinbaseStampIcon.svg",
    category: "Coinbase",
    type: "Government IDs",
  },
  [GitcoinPassport.discord]: {
    weight: 0.5,
    label: "Verified Discord Account",
    icon: "discordStampIcon.svg",
    category: "Discord",
    type: "Social & Professional Platforms",
  },
  [GitcoinPassport.ens]: {
    weight: 0.4,
    label: "Verified Primary ENS",
    icon: "ensStampIcon.svg",
    category: "ENS",
    type: "Blockchain & Crypto Networks",
  },
  [GitcoinPassport.ethEnthusiast]: {
    weight: 10,
    label: "ETH Enthusiast",
    icon: "ethereumStampIcon.svg",
    category: "Ethereum",
    type: "Blockchain & Crypto Networks",
  },
  [GitcoinPassport.ethAdvocate]: {
    weight: 2,
    label: "ETH Advocate",
    icon: "ethereumStampIcon.svg",
    category: "Ethereum",
    type: "Blockchain & Crypto Networks",
  },
  [GitcoinPassport.ethMaxi]: {
    weight: 2,
    label: "ETH Maxi",
    icon: "ethereumStampIcon.svg",
    category: "Ethereum",
    type: "Blockchain & Crypto Networks",
  },
  [GitcoinPassport.ethActive50Days]: {
    weight: 0.5,
    label: "Active on Ethereum over 50 distinct days",
    icon: "ethereumStampIcon.svg",
    category: "Ethereum Activity",
    type: "Blockchain & Crypto Networks",
  },
  [GitcoinPassport.ethTransactionsOver100]: {
    weight: 0.5,
    label: "Execute over 100 transactions on Ethereum",
    icon: "ethereumStampIcon.svg",
    category: "Ethereum Activity",
    type: "Blockchain & Crypto Networks",
  },
  [GitcoinPassport.ethGasMoreThan025]: {
    weight: 1,
    label: "Spend more than 0.25 ETH on gas",
    icon: "ethereumStampIcon.svg",
    category: "Ethereum Activity",
    type: "Blockchain & Crypto Networks",
  },
  [GitcoinPassport.gitcoinGrants10]: {
    weight: 0.5,
    label: "Contributed at least $10",
    icon: "gtcGrantsLightIcon.svg",
    category: "Gitcoin Grants",
    type: "Blockchain & Crypto Networks",
  },
  [GitcoinPassport.gitcoinGrants100]: {
    weight: 2,
    label: "Contributed at least $100",
    icon: "gtcGrantsLightIcon.svg",
    category: "Gitcoin Grants",
    type: "Blockchain & Crypto Networks",
  },
  [GitcoinPassport.gitcoinGrants1000]: {
    weight: 5,
    label: "Contributed at least $1000",
    icon: "gtcGrantsLightIcon.svg",
    category: "Gitcoin Grants",
    type: "Blockchain & Crypto Networks",
  },
  [GitcoinPassport.githubActivity30]: {
    weight: 2,
    label: "Contributions on at least 30 distinct days",
    icon: "githubWhiteStampIcon.svg",
    category: "GitHub",
    type: "Social & Professional Platforms",
  },
  [GitcoinPassport.githubActivity60]: {
    weight: 2,
    label: "Contributions on at least 60 distinct days",
    icon: "githubWhiteStampIcon.svg",
    category: "GitHub",
    type: "Social & Professional Platforms",
  },
  [GitcoinPassport.githubActivity120]: {
    weight: 3,
    label: "Contributions on at least 120 distinct days",
    icon: "githubWhiteStampIcon.svg",
    category: "GitHub",
    type: "Social & Professional Platforms",
  },
  [GitcoinPassport.gnosisSafe]: {
    weight: 0.8,
    label: "Gnosis Safe Signer/Owner",
    icon: "gnosisSafeStampIcon.svg",
    category: "Gnosis Safe",
    type: "Blockchain & Crypto Networks",
  },
  [GitcoinPassport.google]: {
    weight: 0.5,
    label: "Verified Google Account",
    icon: "googleStampIcon.svg",
    category: "Google",
    type: "Social & Professional Platforms",
  },
  [GitcoinPassport.experiencedCommunityStaker]: {
    weight: 2.5,
    label: "Experienced Community Staker",
    icon: "gtcStakingLogoIcon.svg",
    category: "GTC Community Staking",
    type: "Blockchain & Crypto Networks",
  },
  [GitcoinPassport.trustedCitizen]: {
    weight: 4,
    label: "Trusted Citizen",
    icon: "gtcStakingLogoIcon.svg",
    category: "GTC Community Staking",
    type: "Blockchain & Crypto Networks",
  },
  [GitcoinPassport.trustaLabs]: {
    weight: 0.5,
    label: "TrustScan Non-Sybil Account",
    icon: "trustaLabsStampIcon.svg",
    category: "Trusta Labs",
    type: "Blockchain & Crypto Networks",
  },
  [GitcoinPassport.selfStakingBronze]: {
    weight: 1,
    label: "Self Staking Bronze",
    icon: "gtcStakingLogoIcon.svg",
    category: "GTC Staking",
    type: "Blockchain & Crypto Networks",
  },
  [GitcoinPassport.selfStakingSilver]: {
    weight: 2,
    label: "Self Staking Silver",
    icon: "gtcStakingLogoIcon.svg",
    category: "GTC Staking",
    type: "Blockchain & Crypto Networks",
  },
  [GitcoinPassport.selfStakingGold]: {
    weight: 3,
    label: "Self Staking Gold",
    icon: "gtcStakingLogoIcon.svg",
    category: "GTC Staking",
    type: "Blockchain & Crypto Networks",
  },
  [GitcoinPassport.guildAdmin]: {
    weight: 0.7,
    label: "Owner or Administrator of one or more guilds",
    icon: "guildXYZStampIcon.svg",
    category: "Guild",
    type: "Blockchain & Crypto Networks",
  },
  [GitcoinPassport.guildMember]: {
    weight: 0.5,
    label: "Member with 1 or more roles in Gitcoin Passport Guild",
    icon: "guildXYZStampIcon.svg",
    category: "Guild",
    type: "Blockchain & Crypto Networks",
  },
  [GitcoinPassport.holonymGovIdProvider]: {
    weight: 16,
    label:
      "Proven uniqueness using Holonym KYC with government ID or ePassport",
    icon: "holonymStampIcon.svg",
    category: "Holonym",
    type: "Government IDs",
  },
  [GitcoinPassport.idenaStateHuman]: {
    weight: 2,
    label: "Idena Identity State - Human",
    icon: "idenaStampIcon.svg",
    category: "Idena",
    type: "Blockchain & Crypto Networks",
  },
  [GitcoinPassport.idenaStateNewbie]: {
    weight: 6,
    label: "Idena Identity State - Newbie",
    icon: "idenaStampIcon.svg",
    category: "Idena",
    type: "Blockchain & Crypto Networks",
  },
  [GitcoinPassport.idenaStateVerified]: {
    weight: 2,
    label: "Idena Identity State - Verified",
    icon: "idenaStampIcon.svg",
    category: "Idena",
    type: "Blockchain & Crypto Networks",
  },
  [GitcoinPassport.lens]: {
    weight: 0.9,
    label: "Verified Lens Handle",
    icon: "lensWhiteStampIcon.svg",
    category: "Lens",
    type: "Blockchain & Crypto Networks",
  },
  [GitcoinPassport.linkedin]: {
    weight: 1.5,
    label: "Verified LinkedIn Account",
    icon: "linkedinStampIcon.svg",
    category: "LinkedIn",
    type: "Social & Professional Platforms",
  },
  [GitcoinPassport.nft]: {
    weight: 1,
    label: "Holds at least 1 NFT (ERC-721)",
    icon: "nftStampIcon.svg",
    category: "NFT",
    type: "Blockchain & Crypto Networks",
  },
  [GitcoinPassport.nftScore50]: {
    weight: 10,
    label: "Digital Collector",
    icon: "nftStampIcon.svg",
    category: "NFT",
    type: "Blockchain & Crypto Networks",
  },
  [GitcoinPassport.nftScore75]: {
    weight: 2,
    label: "Art Aficionado",
    icon: "nftStampIcon.svg",
    category: "NFT",
    type: "Blockchain & Crypto Networks",
  },
  [GitcoinPassport.nftScore90]: {
    weight: 2,
    label: "NFT Visionary",
    icon: "nftStampIcon.svg",
    category: "NFT",
    type: "Blockchain & Crypto Networks",
  },
  [GitcoinPassport.snapshotProposalsProvider]: {
    weight: 0.8,
    label: "Created a DAO proposal that was voted on by at least 1 account",
    icon: "snapshotStampIcon.svg",
    category: "Snapshot",
    type: "Blockchain & Crypto Networks",
  },
  [GitcoinPassport.zkSyncEra]: {
    weight: 0.6,
    label: "Verified Transactor",
    icon: "zksyncStampIcon.svg",
    category: "ZkSync",
    type: "Blockchain & Crypto Networks",
  },
  [GitcoinPassport.zkSyncScore20]: {
    weight: 1.7,
    label: "Engagement Explorer",
    icon: "zksyncStampIcon.svg",
    category: "ZkSync",
    type: "Blockchain & Crypto Networks",
  },
  [GitcoinPassport.zkSyncScore50]: {
    weight: 1.7,
    label: "L2 Believer",
    icon: "zksyncStampIcon.svg",
    category: "ZkSync",
    type: "Blockchain & Crypto Networks",
  },
  [GitcoinPassport.zkSyncScore5]: {
    weight: 1.7,
    label: "zkSync Champion",
    icon: "zksyncStampIcon.svg",
    category: "ZkSync",
    type: "Blockchain & Crypto Networks",
  },
  [GitcoinPassport.outdid]: {
    weight: 10,
    label: "ZK-prove your identity with Outdid",
    icon: "outdidStampIcon.svg",
    category: "Outdid",
    type: "Government IDs",
  },
  [GitcoinPassport.binanceBABT]: {
    weight: 16,
    label: "Verified Binance Account",
    icon: "binanceStamp.svg",
    category: "BinanceBABT",
    type: "Government IDs",
  },
};

export const gitcoinPassportMapping = (key: GitcoinPassport) =>
  gitcoinPassportData[key];
