export enum GitcoinPassport {
  beginnerCommunityStaker = "BeginnerCommunityStaker",
  brightId = "Brightid",
  civicCaptcha = "CivicCaptchaPass",
  civicLiveness = "CivicLivenessPass",
  civicUniqueness = "CivicUniquenessPass",
  coinbaseDual = "CoinbaseDualVerification",
  discord = "Discord",
  ens = "Ens",
  ethActive50Days = "ETHDaysActive#50",
  ethGasMoreThan025 = "ETHGasSpent#0.25",
  ethTransactionsOver100 = "ETHnumTransactions#100",
  ethEnthusiast = "ETHScore#50",
  ethAdvocate = "ETHScore#75",
  ethMaxi = "ETHScore#90",
  experiencedCommunityStaker = "ExperiencedCommunityStaker",
  gitcoinGrants10 = "GitcoinContributorStatistics#totalContributionAmountGte#10",
  gitcoinGrants100 = "GitcoinContributorStatistics#totalContributionAmountGte#100",
  gitcoinGrants1000 = "GitcoinContributorStatistics#totalContributionAmountGte#1000",
  githubActivity30 = "githubContributionActivityGte#30",
  githubActivity60 = "githubContributionActivityGte#60",
  githubActivity120 = "githubContributionActivityGte#120",
  gnosisSafe = "GnosisSafe",
  google = "Google",
  guildAdmin = "GuildAdmin",
  guildMember = "GuildPassportMember",
  holonymGovIdProvider = "HolonymGovIdProvider",
  idenaStateHuman = "IdenaState#Human",
  idenaStateNewbie = "IdenaState#Newbie",
  idenaStateVerified = "IdenaState#Verified",
  lens = "Lens",
  linkdein = "Linkdein",
  nft = "NFT",
  nftScore50 = "NFTScore#50",
  nftScore75 = "NFTScore#75",
  nftScore90 = "NFTScore#90",
  selfStakingBronze = "SelfStakingBronze",
  selfStakingGold = "SelfStakingGold",
  selfStakingSilver = "SelfStakingSilver",
  snapshotProposalsProvider = "SnapshotProposalsProvider",
  trustaLabs = "TrustaLabs",
  trustedCitizen = "TrustedCitizen",
  zkSyncEra = "ZkSyncEra",
  zkSyncScore20 = "zkSyncScore#20",
  zkSyncScore50 = "zkSyncScore#50",
  zkSyncScore5 = "zkSyncScore#5",
  outdid = "Outdid",
  binanceBABT = "BinanceBABT",
}

export const gitcoinPassportMapping = (key: GitcoinPassport) => {
  return {
    [GitcoinPassport.beginnerCommunityStaker]: {
      weight: 1.513,
      label: "Beginner Community Staker",
      icon: "gtcStakingLogoIcon.svg",
      category: "GTC Community Staking",
      type: "Blockchain & Crypto",
    },
    [GitcoinPassport.brightId]: {
      weight: 0.802,
      label: "Verified BrightID",
      icon: "brightidStampIcon.svg",
      category: "BrightID",
      type: "Blockchain & Crypto",
    },
    [GitcoinPassport.civicCaptcha]: {
      weight: 1.014,
      label: "Civic CAPTCHA Pass",
      icon: "civicStampIcon.svg",
      category: "Civic",
      type: "Biometric Verification",
    },
    [GitcoinPassport.civicLiveness]: {
      weight: 3.004,
      label: "Civic Liveness Pass",
      icon: "civicStampIcon.svg",
      category: "Civic",
      type: "Biometric Verification",
    },
    [GitcoinPassport.civicUniqueness]: {
      weight: 6.005,
      label: "Civic Uniqueness Pass",
      icon: "civicStampIcon.svg",
      category: "Civic",
      type: "Biometric Verification",
    },
    [GitcoinPassport.coinbaseDual]: {
      weight: 16.042,
      label: "Coinbase Verified ID",
      icon: "coinbaseStampIcon.svg",
      category: "Coinbase",
      type: "Government ID",
    },
    [GitcoinPassport.discord]: {
      weight: 0.516,
      label: "Verified Discord Account",
      icon: "discordStampIcon.svg",
      category: "Discord",
      type: "Social & Professional",
    },
    [GitcoinPassport.ens]: {
      weight: 0.408,
      label: "Verified Primary ENS",
      icon: "ensStampIcon.svg",
      category: "ENS",
      type: "Blockchain & Crypto",
    },
    [GitcoinPassport.ethEnthusiast]: {
      weight: 10.012,
      label: "ETH Enthusiast",
      icon: "ethereumStampIcon.svg",
      category: "Ethereum",
      type: "Blockchain & Crypto",
    },
    [GitcoinPassport.ethAdvocate]: {
      weight: 2.001,
      label: "ETH Advocate",
      icon: "ethereumStampIcon.svg",
      category: "Ethereum",
      type: "Blockchain & Crypto",
    },
    [GitcoinPassport.ethMaxi]: {
      weight: 2.009,
      label: "ETH Maxi",
      icon: "ethereumStampIcon.svg",
      category: "Ethereum",
      type: "Blockchain & Crypto",
    },
    [GitcoinPassport.ethActive50Days]: {
      weight: 0.507,
      label: "50+ days ETH activity",
      icon: "ethereumStampIcon.svg",
      category: "Ethereum Activity",
      type: "Blockchain & Crypto",
    },
    [GitcoinPassport.ethTransactionsOver100]: {
      weight: 0.51,
      label: "100+ ETH transactions",
      icon: "ethereumStampIcon.svg",
      category: "Ethereum Activity",
      type: "Blockchain & Crypto",
    },
    [GitcoinPassport.ethGasMoreThan025]: {
      weight: 1.003,
      label: "ETH gas > 0.25",
      icon: "ethereumStampIcon.svg",
      category: "Ethereum Activity",
      type: "Blockchain & Crypto",
    },
    [GitcoinPassport.gitcoinGrants10]: {
      weight: 0.523,
      label: "Contributed $10+",
      icon: "gtcGrantsLightIcon.svg",
      category: "Gitcoin Grants",
      type: "Blockchain & Crypto",
    },
    [GitcoinPassport.gitcoinGrants100]: {
      weight: 2.017,
      label: "Contributed $100+",
      icon: "gtcGrantsLightIcon.svg",
      category: "Gitcoin Grants",
      type: "Blockchain & Crypto",
    },
    [GitcoinPassport.gitcoinGrants1000]: {
      weight: 5.018,
      label: "Contributed $1000+",
      icon: "gtcGrantsLightIcon.svg",
      category: "Gitcoin Grants",
      type: "Blockchain & Crypto",
    },
    [GitcoinPassport.githubActivity30]: {
      weight: 2.02,
      label: "30+ days GitHub activity",
      icon: "githubWhiteStampIcon.svg",
      category: "GitHub",
      type: "Social & Professional",
    },
    [GitcoinPassport.githubActivity60]: {
      weight: 2.021,
      label: "60+ days GitHub activity",
      icon: "githubWhiteStampIcon.svg",
      category: "GitHub",
      type: "Social & Professional",
    },
    [GitcoinPassport.githubActivity120]: {
      weight: 3.019,
      label: "120+ days GitHub activity",
      icon: "githubWhiteStampIcon.svg",
      category: "GitHub",
      type: "Social & Professional",
    },
    [GitcoinPassport.gnosisSafe]: {
      weight: 0.822,
      label: "Gnosis Safe Signer/Owner",
      icon: "gnosisSafeStampIcon.svg",
      category: "Gnosis Safe",
      type: "Blockchain & Crypto",
    },
    [GitcoinPassport.google]: {
      weight: 0.525,
      label: "Verified Google Account",
      icon: "googleStampIcon.svg",
      category: "Google",
      type: "Social & Professional",
    },
    [GitcoinPassport.experiencedCommunityStaker]: {
      weight: 2.515,
      label: "Experienced Community Staker",
      icon: "gtcStakingLogoIcon.svg",
      category: "GTC Community Staking",
      type: "Blockchain & Crypto",
    },
    [GitcoinPassport.trustedCitizen]: {
      weight: 4.041,
      label: "Trusted Citizen",
      icon: "gtcStakingLogoIcon.svg",
      category: "GTC Community Staking",
      type: "Blockchain & Crypto",
    },
    [GitcoinPassport.trustaLabs]: {
      weight: 0.511,
      label: "TrustScan Non-Sybil Account",
      icon: "trustaLabsStampIcon.svg",
      category: "Trusta Labs",
      type: "Blockchain & Crypto",
    },
    [GitcoinPassport.selfStakingBronze]: {
      weight: 1.036,
      label: "Self Staking Bronze",
      icon: "gtcStakingLogoIcon.svg",
      category: "GTC Staking",
      type: "Blockchain & Crypto",
    },
    [GitcoinPassport.selfStakingSilver]: {
      weight: 2.038,
      label: "Self Staking Silver",
      icon: "gtcStakingLogoIcon.svg",
      category: "GTC Staking",
      type: "Blockchain & Crypto",
    },
    [GitcoinPassport.selfStakingGold]: {
      weight: 3.037,
      label: "Self Staking Gold",
      icon: "gtcStakingLogoIcon.svg",
      category: "GTC Staking",
      type: "Blockchain & Crypto",
    },
    [GitcoinPassport.guildAdmin]: {
      weight: 0.724,
      label: "Guild Admin",
      icon: "guildXYZStampIcon.svg",
      category: "Guild",
      type: "Blockchain & Crypto",
    },
    [GitcoinPassport.guildMember]: {
      weight: 0.54,
      label: "Gitcoin Passport Guild Member",
      icon: "guildXYZStampIcon.svg",
      category: "Guild",
      type: "Blockchain & Crypto",
    },
    [GitcoinPassport.holonymGovIdProvider]: {
      weight: 16.026,
      label: "Holonym Government ID",
      icon: "holonymStampIcon.svg",
      category: "Holonym",
      type: "Government ID",
    },
    [GitcoinPassport.idenaStateHuman]: {
      weight: 2.027,
      label: "Idena Identity State - Human",
      icon: "idenaStampIcon.svg",
      category: "Idena",
      type: "Blockchain & Crypto",
    },
    [GitcoinPassport.idenaStateNewbie]: {
      weight: 6.028,
      label: "Idena Identity State - Newbie",
      icon: "idenaStampIcon.svg",
      category: "Idena",
      type: "Blockchain & Crypto",
    },
    [GitcoinPassport.idenaStateVerified]: {
      weight: 2.029,
      label: "Idena Identity State - Verified",
      icon: "idenaStampIcon.svg",
      category: "Idena",
      type: "Blockchain & Crypto",
    },
    [GitcoinPassport.lens]: {
      weight: 0.93,
      label: "Verified Lens Handle",
      icon: "lensWhiteStampIcon.svg",
      category: "Lens",
      type: "Blockchain & Crypto",
    },
    [GitcoinPassport.linkdein]: {
      weight: 1.531,
      label: "Verified LinkedIn Account",
      icon: "linkedinStampIcon.svg",
      category: "LinkedIn",
      type: "Social & Professional",
    },
    [GitcoinPassport.nft]: {
      weight: 1.032,
      label: "NFT Holder",
      icon: "nftStampIcon.svg",
      category: "NFT",
      type: "Blockchain & Crypto",
    },
    [GitcoinPassport.nftScore50]: {
      weight: 10.033,
      label: "Digital Collector",
      icon: "nftStampIcon.svg",
      category: "NFT",
      type: "Blockchain & Crypto",
    },
    [GitcoinPassport.nftScore75]: {
      weight: 2.034,
      label: "Art Aficionado",
      icon: "nftStampIcon.svg",
      category: "NFT",
      type: "Blockchain & Crypto",
    },
    [GitcoinPassport.nftScore90]: {
      weight: 2.035,
      label: "NFT Visionary",
      icon: "nftStampIcon.svg",
      category: "NFT",
      type: "Blockchain & Crypto",
    },
    [GitcoinPassport.snapshotProposalsProvider]: {
      weight: 0.839,
      label: "Snapshot Proposal Creator",
      icon: "snapshotStampIcon.svg",
      category: "Snapshot",
      type: "Blockchain & Crypto",
    },
    [GitcoinPassport.zkSyncEra]: {
      weight: 0.606,
      label: "Verified Transactor",
      icon: "zksyncStampIcon.svg",
      category: "ZkSync",
      type: "Blockchain & Crypto",
    },
    [GitcoinPassport.zkSyncScore20]: {
      weight: 1.67,
      label: "Engagement Explorer",
      icon: "zksyncStampIcon.svg",
      category: "ZkSync",
      type: "Blockchain & Crypto",
    },
    [GitcoinPassport.zkSyncScore50]: {
      weight: 1.67,
      label: "Blockchain Believer",
      icon: "zksyncStampIcon.svg",
      category: "ZkSync",
      type: "Blockchain & Crypto",
    },
    [GitcoinPassport.zkSyncScore5]: {
      weight: 1.67,
      label: "zkSync Champion",
      icon: "zksyncStampIcon.svg",
      category: "ZkSync",
      type: "Blockchain & Crypto",
    },
    [GitcoinPassport.outdid]: {
      weight: 10,
      label: "Outdid Verified ZK ID",
      icon: "outdidStampIcon.svg",
      category: "Outdid",
      type: "Government ID",
    },
    [GitcoinPassport.binanceBABT]: {
      weight: 16.021,
      label: "Verified Binance Account",
      icon: "binanceStamp.svg",
      category: "BinanceBABT",
      type: "Government ID",
    },
  }[key];
};
