export const regexEns = /^.+\.(eth|xyz|app|luxe|kred|art|ceo|club)$/i,
  regexLens = /^[a-z0-9-]+\.lens$/i,
  regexDotbit = /^.+\.bit$/i,
  regexEth = /^0x[a-fA-F0-9]{40}$/i,
  regexBtc = /^[13][a-km-zA-HJ-NP-Z1-9]{25,34}$/,
  regexSns = /^.+\.sol$/i,
  regexSolana = /^[1-9A-HJ-NP-Za-km-z]{32,44}$/,
  regexTwitter = /^[A-Za-z0-9_]{1,15}$/i,
  regexFarcaster = /^[A-Za-z0-9_-]{1,61}(?:|\.eth)(?:|\.farcaster)$/i,
  regexUnstoppableDomains =
    /^.+\.(crypto|888|nft|blockchain|bitcoin|dao|x|klever|hi|zil|kresus|polygon|wallet|binanceus|anime|go|manga|eth)$/i,
  regexSpaceid = /^.+\.(bnb|arb)$/i,
  regexCrossbell = /^.+\.csb$/i,
  regexGenome = /^.+\.gno$/i,
  regexAvatar = /^0x[a-f0-9]{66}$/i,
  regexEIP = /^eip155:(\d+)\/(erc1155|erc721):(.+)\/(.+)$/,
  regexDomain = /^(?:https?:\/\/)?(?:[^@\/\n]+@)?(?:www\.)?([^:\/\n]+)/,
  regexCluster = /^[\w-]+\/[\w-]+$/;
