export enum NetworkType {
  Ethereum = "ethereum",
  BSC = "binance_smart_chain",
  Base = "base",
  Arb = "arbitrum",
  Polygon = "polygon",
  OP = "optimism",
  Fantom = "fantom",
  Zks = "zksync",
  AVA = "avalanche",
  Crossbell = "crossbell",
  Farcaster = "farcaster",
  Conflux = "conflux",
  ETC = "ethereum_classic",
  Aptos = "aptos",
  Arweave = "arweave",
  Celo = "celo",
  XDai = "xdai",
}

export interface NetworkMetaData {
  key: string;
  primaryColor: string;
  bgColor: string;
  icon: string;
  label: string;
  scanPrefix: string;
  lightColor?: string;
  darkColor?: string;
}

export const networkData: { [key in NetworkType]: NetworkMetaData } = {
  [NetworkType.Ethereum]: {
    key: NetworkType.Ethereum,
    primaryColor: "#5298FF",
    bgColor: "#ebf3ff",
    lightColor: "#FFFFFF",
    darkColor: "#000000",
    label: "Ethereum",
    scanPrefix: "https://etherscan.io/",
    icon: "icons/icon-ethereum.svg",
  },
  [NetworkType.Polygon]: {
    key: NetworkType.Polygon,
    primaryColor: "#8465CB",
    bgColor: "#efeaf8",
    lightColor: "#FFFFFF",
    darkColor: "#000000",
    label: "Polygon",
    scanPrefix: "https://polygonscan.com/",
    icon: "",
  },
  [NetworkType.AVA]: {
    key: NetworkType.AVA,
    primaryColor: "",
    bgColor: "",
    lightColor: "",
    darkColor: "",
    label: "Avalanche",
    scanPrefix: "https://avascan.info/",
    icon: "",
  },
  [NetworkType.Aptos]: {
    key: NetworkType.Aptos,
    primaryColor: "",
    bgColor: "",
    lightColor: "",
    darkColor: "",
    label: "Aptos",
    scanPrefix: "https://aptoscan.com/",
    icon: "",
  },
  [NetworkType.Arb]: {
    key: NetworkType.Arb,
    primaryColor: "",
    bgColor: "",
    lightColor: "",
    darkColor: "",
    label: "Arbitrum",
    scanPrefix: "https://arbiscan.io/",
    icon: "",
  },
  [NetworkType.Arweave]: {
    key: NetworkType.Arweave,
    primaryColor: "",
    bgColor: "",
    lightColor: "",
    darkColor: "",
    label: "Arweave",
    scanPrefix: "https://viewblock.io/arweave/",
    icon: "",
  },
  [NetworkType.BSC]: {
    key: NetworkType.BSC,
    primaryColor: "",
    bgColor: "",
    lightColor: "",
    darkColor: "",
    label: "Binance Smart Chain",
    scanPrefix: "https://bscscan.com/",
    icon: "",
  },
  [NetworkType.Base]: {
    key: NetworkType.Base,
    primaryColor: "",
    bgColor: "",
    lightColor: "",
    darkColor: "",
    label: "Base",
    scanPrefix: "https://basescan.org/",
    icon: "",
  },
  [NetworkType.Celo]: {
    key: NetworkType.Celo,
    primaryColor: "",
    bgColor: "",
    lightColor: "",
    darkColor: "",
    label: "Celo",
    scanPrefix: "https://celoscan.io/",
    icon: "",
  },
  [NetworkType.Conflux]: {
    key: NetworkType.Conflux,
    primaryColor: "",
    bgColor: "",
    lightColor: "",
    darkColor: "",
    label: "Conflux",
    scanPrefix: "https://www.confluxscan.io/",
    icon: "",
  },
  [NetworkType.Crossbell]: {
    key: NetworkType.Crossbell,
    primaryColor: "",
    bgColor: "",
    lightColor: "",
    darkColor: "",
    label: "Crossbell",
    scanPrefix: "https://scan.crossbell.io/",
    icon: "",
  },
  [NetworkType.ETC]: {
    key: NetworkType.Ethereum,
    primaryColor: "",
    bgColor: "",
    lightColor: "",
    darkColor: "",
    label: "Ethereum Classic",
    scanPrefix: "https://etc.blockscout.com/",
    icon: "",
  },
  [NetworkType.Fantom]: {
    key: NetworkType.Fantom,
    primaryColor: "",
    bgColor: "",
    lightColor: "",
    darkColor: "",
    label: "Fantom",
    scanPrefix: "https://ftmscan.com/",
    icon: "",
  },
  [NetworkType.Farcaster]: {
    key: NetworkType.Farcaster,
    primaryColor: "#8a63d2",
    bgColor: "#efeaf8",
    lightColor: "",
    darkColor: "",
    label: "Farcaster",
    scanPrefix: "https://casterscan.com/",
    icon: "",
  },
  [NetworkType.OP]: {
    key: NetworkType.OP,
    primaryColor: "",
    bgColor: "",
    lightColor: "",
    darkColor: "",
    label: "Optimism",
    scanPrefix: "https://optimistic.etherscan.io/",
    icon: "",
  },
  [NetworkType.Zks]: {
    key: NetworkType.OP,
    primaryColor: "",
    bgColor: "",
    lightColor: "",
    darkColor: "",
    label: "zksync",
    scanPrefix: "https://explorer.zksync.io/",
    icon: "",
  },
  [NetworkType.XDai]: {
    key: NetworkType.XDai,
    primaryColor: "",
    bgColor: "",
    lightColor: "",
    darkColor: "",
    label: "XDai",
    scanPrefix: "https://gnosisscan.io/",
    icon: "",
  },
};

export const NetworkMapping = (network: NetworkType) => {
  return (
    networkData[network] ?? {
      key: network,
      color: "#000000",
      icon: "",
      label: network,
    }
  );
};
