export enum Tag {
    Collectible = 'collectible',
    Donation = 'donation',
    Exchange = 'exchange',
    Governance = 'governance',
    Social = 'social',
    Transaction = 'transaction',
}

export enum Type {
    Transfer = 'transfer',
    Mint = 'mint',
    Burn = 'burn',
    Withdraw = 'withdraw',
    Deposit = 'deposit',
    Swap = 'swap',
    Liquidity = 'liquidity',
    Trade = 'trade',
    Poap = 'poap',
    Post = 'post',
    Revise = 'revise',
    Comment = 'comment',
    Share = 'share',
    Profile = 'profile',
    Follow = 'follow',
    Unfollow = 'unfollow',
    Like = 'like',
    Propose = 'propose',
    Vote = 'vote',
    Launch = 'launch',
    Donate = 'donate',
}

export enum CardType {
    AchievementBurn = 1,
    AchievementReceive = 2,
    CollectibleBurn = 3,
    CollectibleIn = 4,
    CollectibleMint = 5,
    CollectibleOut = 6,
    DonationDonate = 7,
    DonationLaunch = 8,
    GovernancePropose = 9,
    GovernanceVote = 10,
    NoteCreate = 11,
    NoteEdit = 12,
    NoteLink = 13,
    NoteBurn = 14,
    ProfileBurn = 15,
    ProfileCreate = 16,
    ProfileLink = 17,
    TokenIn = 18,
    TokenLiquidity = 19,
    TokenOut = 20,
    TokenStake = 21,
    TokenSwap = 22,
    UnknownBurn = 23,
    UnknownCancel = 24,
    UnknownIn = 25,
    UnknownOut = 26,
}