export enum Tag {
    Collectible = 'collectible',
    Donation = 'donation',
    Exchange = 'exchange',
    Governance = 'governance',
    Social = 'social',
    Transaction = 'transaction',
}

export enum Type {
    Transfer = 'transfer',
    Mint = 'mint',
    Burn = 'burn',
    Withdraw = 'withdraw',
    Deposit = 'deposit',
    Swap = 'swap',
    Liquidity = 'liquidity',
    Trade = 'trade',
    Poap = 'poap',
    Post = 'post',
    Revise = 'revise',
    Comment = 'comment',
    Share = 'share',
    Profile = 'profile',
    Follow = 'follow',
    Unfollow = 'unfollow',
    Like = 'like',
    Propose = 'propose',
    Vote = 'vote',
    Launch = 'launch',
    Donate = 'donate',
}