export enum Tag {
  Collectible = "collectible",
  Donation = "donation",
  Exchange = "exchange",
  Governance = "governance",
  Social = "social",
  MetaVerse = "metaverse",
  Transaction = "transaction",
}

export enum Type {
  Transfer = "transfer",
  Mint = "mint",
  Burn = "burn",
  Withdraw = "withdraw",
  Deposit = "deposit",
  Swap = "swap",
  Liquidity = "liquidity",
  Trade = "trade",
  Poap = "poap",
  Post = "post",
  Revise = "revise",
  Comment = "comment",
  Share = "share",
  Profile = "profile",
  Follow = "follow",
  Unfollow = "unfollow",
  Like = "like",
  Propose = "propose",
  Vote = "vote",
  Launch = "launch",
  Donate = "donate",
  Approval = "approval",
  Edit = 'edit',
}

export enum Networks {
  Ethereum = "ethereum",
  BSC = "binance_smart_chain",
  Base = "base",
  Arb = "arbitrum",
  Matic = "polygon",
  OP = "optimism",
  Fantom = "fantom",
  Zks = "zksync",
  AVA = "avalanche",
  Crossbell = "crossbell",
  Farcaster = "farcaster",
  Conflux = "conflux",
  ETC = "ethereum_classic",
  Aptos = "aptos",
  Arweave = "arweave",
  Celo = "celo",
  XDai = "xdai",
}
